#!/bin/bash

PLUGIN_DIR="${PLUGIN_DIR:-$HOME/.config/sketchybar/plugins}"

sketchybar --add graph cpu_graph right 50 \
           --set cpu_graph graph.color=0xff66ccff \
                          graph.fill_color=0x4066ccff \
                          graph.line_width=2.0 \
                          background.drawing=off \
                          update_freq=5 \
                          label.padding_left=4 \
                          label.padding_right=4 \
                          label.font="SF Pro:Medium:11.0" \
                          icon.drawing=off \
                          script="$PLUGIN_DIR/cpu.sh"
