#!/bin/bash

PLUGIN_DIR="${PLUGIN_DIR:-$HOME/.config/sketchybar/plugins}"

sketchybar --add item media center \
           --set media drawing=off \
                       icon="" \
                       icon.font="SF Pro:Medium:13.0" \
                       icon.padding_left=8 \
                       icon.padding_right=4 \
                       label.padding_left=4 \
                       label.padding_right=8 \
                       label.max_chars=40 \
                       script="$PLUGIN_DIR/media.sh" \
           --subscribe media media_change
