#!/usr/bin/env bash

sketchybar --add event aerospace_mode_change \
           --add item mode_indicator left \
           --subscribe mode_indicator aerospace_mode_change \
           --set mode_indicator drawing=off \
                                background.color=0xff5e81ac \
                                background.corner_radius=10 \
                                background.height=28 \
                                background.drawing=off \
                                icon.padding_left=8 \
                                icon.padding_right=4 \
                                label.padding_left=4 \
                                label.padding_right=8 \
                                label.font="SF Pro:Bold:11.0" \
                                script="$PLUGIN_DIR/mode_indicator.sh"
